export const tasksUrl = 'https://api.todoist.com/rest/v2/tasks'
export const labelsUrl = 'https://api.todoist.com/rest/v2/labels'
export const projectsUrl = 'https://api.todoist.com/rest/v2/projects'
export const syncUrl = 'https://api.todoist.com/sync/v9/sync'
export const completedUrl = 'https://api.todoist.com/sync/v9/completed/get_all'
export const itemUrl = 'https://api.todoist.com/sync/v9/items/get'
export const getProjectUrl = 'https://api.todoist.com/sync/v9/projects/get'
